server:
  port: 3000

db:
  type: 'postgres'
  host: 'localhost'
  port: 15432
  username: 'nestjs'
  password: 'nestjs'
  database: 'nestjs'
  synchronize: true

jwt:
  expiredIn: 3600
  secret: 'secret-key'
